Fix test_density for histogram
IntelPython/dpnp pull request #1115
Opened 2022-01-25 12:47 UTC by LukichevaPolina

2022-01-25 13:51 UTC, densmirn approved these changes

2022-01-27 09:20 UTC, Alexander-Makaryev requested changes
Looks like dpnp.sum returns array instead scalar (as in original Numpy) and this is a reason why we have to change assert functions. Could you please check it and fix if it is so instead of using another functions?

2023-06-05 15:12 UTC, intel-python-devops commented
Can one of the admins verify this patch?

2024-06-27 14:08 UTC, antonwolfy commented
#1785 covers that PR

2024-06-27 14:08 UTC, closed without merging