Add dtype and manipulation functions
IntelPython/dpnp pull request #1566
Opened 2023-09-21 16:18 UTC by npolina4

Add dtype and manipulation functions and tests.
Manipulation functions: dpnp.broadcast_arrays,  dpnp.atleast_2d, dpnp.atleast_3d, dpnp.repeat, dpnp.vstack
Data Type functions: dpnp.can_cast, dpnp.finfo, dpnp.iinfi, dpnp.isdtype

- [X] Have you provided a meaningful PR description?
- [x] Have you added a test, reproducer or referred to issue with a reproducer?
- [x] Have you tested your changes locally for CPU and GPU devices?
- [x] Have you made sure that new changes do not introduce compiler warnings?
- [ ] Have you checked performance impact of proposed changes?

2023-09-21 23:52 UTC, vtavana commented on dpnp/dpnp_algo/dpnp_algo.pyx
> -include "dpnp_algo_manipulation.pxi"
I had to remove `${CMAKE_CURRENT_SOURCE_DIR}/dpnp_algo_manipulation.pxi` from `/dpnp/dpnp_algo/CMakeLists.txt` to be able to compile the code, did not you?

I also had to remove `cpdef dpnp_descriptor dpnp_repeat(dpnp_descriptor array1, repeats, axes=*)` from `dpnp/dpnp_algo/dpnp_algo.pxd`.

2023-09-21 23:52 UTC, vtavana commented on dpnp/dpnp_iface_manipulation.py
> +    Examples
Could you please add "Limitations", "Returns", and "See Also" sections similar to `hstack`?

2023-09-21 23:52 UTC, vtavana commented on dpnp/dpnp_iface_manipulation.py
> +def vstack(tup, *, dtype=None, casting="same_kind"):
Could you remove `tests/test_arraymanipulation.py::TestVstack::test_generator` from skipped tests table and modify the test accordingly to be passed?

Could you also move `tests/test_random.py::TestPermutationsTestShuffle::test_shuffle1[lambda x: dpnp.vstack([x, x]).T]` to skipped test table for gpu_no_f64?

2023-09-21 23:52 UTC, vtavana commented on tests/test_arraymanipulation.py
> +    usm_arrays = [dpnp.asarray(Xnp) for Xnp in np_arrays]
```suggestion
    dpnp_arrays = [dpnp.asarray(Xnp) for Xnp in np_arrays]
```
And rename other occurrence as well.

2023-09-21 23:52 UTC, vtavana commented on dpnp/dpnp_iface_manipulation.py
> +    Parameters:
```suggestion
    Parameters
    ----------
```
Could you do this for other similar cases as well for consistency?

2023-09-21 23:52 UTC, vtavana commented on dpnp/dpnp_iface_manipulation.py
> +    -----------
```suggestion
    Notes
    -----
```

2023-09-21 23:52 UTC, vtavana commented on dpnp/dpnp_iface_manipulation.py
> +    If from is a scalar or array scalar, also returns True if the scalar value can
```suggestion
    If `from` is a scalar or array scalar, also returns `True` if the scalar value can
```

2023-09-21 23:52 UTC, vtavana commented on dpnp/dpnp_iface_manipulation.py
>  ):
Could you modify line 398? ` dtype -> `dtype`

2023-09-21 23:52 UTC, vtavana commented on dpnp/dpnp_iface_manipulation.py
>      Otherwise the function will be executed sequentially on CPU.
remove it?

2023-09-25 16:38 UTC, vtavana commented
It seems we do not to skip the fallowing tests anymore.

tests/third_party/cupy/manipulation_tests/test_dims.py::TestBroadcast_param_0_{shapes=[(), ()]}::test_broadcast_arrays
tests/third_party/cupy/manipulation_tests/test_dims.py::TestBroadcast_param_1_{shapes=[(0,), (0,)]}::test_broadcast_arrays
tests/third_party/cupy/manipulation_tests/test_dims.py::TestBroadcast_param_2_{shapes=[(1,), (1,)]}::test_broadcast_arrays
tests/third_party/cupy/manipulation_tests/test_dims.py::TestBroadcast_param_3_{shapes=[(2,), (2,)]}::test_broadcast_arrays
tests/third_party/cupy/manipulation_tests/test_dims.py::TestBroadcast_param_4_{shapes=[(0,), (1,)]}::test_broadcast_arrays
tests/third_party/cupy/manipulation_tests/test_dims.py::TestBroadcast_param_5_{shapes=[(2, 3), (1, 3)]}::test_broadcast_arrays
tests/third_party/cupy/manipulation_tests/test_dims.py::TestBroadcast_param_6_{shapes=[(2, 1, 3, 4), (3, 1, 4)]}::test_broadcast_arrays
tests/third_party/cupy/manipulation_tests/test_dims.py::TestBroadcast_param_7_{shapes=[(4, 3, 2, 3), (2, 3)]}::test_broadcast_arrays
tests/third_party/cupy/manipulation_tests/test_dims.py::TestBroadcast_param_8_{shapes=[(2, 0, 1, 1, 3), (2, 1, 0, 0, 3)]}::test_broadcast_arrays
tests/third_party/cupy/manipulation_tests/test_dims.py::TestBroadcast_param_9_{shapes=[(0, 1, 1, 3), (2, 1, 0, 0, 3)]}::test_broadcast_arrays
tests/third_party/cupy/manipulation_tests/test_dims.py::TestBroadcast_param_10_{shapes=[(0, 1, 1, 0, 3), (5, 2, 0, 1, 0, 0, 3), (2, 1, 0, 0, 0, 3)]}::test_broadcast_arrays
tests/third_party/cupy/manipulation_tests/test_dims.py::TestInvalidBroadcast_param_0_{shapes=[(3,), (2,)]}::test_invalid_broadcast_arrays
tests/third_party/cupy/manipulation_tests/test_dims.py::TestInvalidBroadcast_param_1_{shapes=[(3, 2), (2, 3)]}::test_invalid_broadcast_arrays
tests/third_party/cupy/manipulation_tests/test_dims.py::TestInvalidBroadcast_param_2_{shapes=[(3, 2), (3, 4)]}::test_invalid_broadcast_arrays
tests/third_party/cupy/manipulation_tests/test_dims.py::TestInvalidBroadcast_param_3_{shapes=[(0,),(2,)]}::test_invalid_broadcast_arrays

2023-09-25 21:54 UTC, vlad-perevezentsev commented on dpnp/dpnp_iface_types.py
> +def finfo(dtype):
Could you add tests for these new functions(`finfo()`, `isdtype()`, `iinfo()`) to increase test coverage ?

2023-09-29 16:08 UTC, vtavana commented on dpnp/dpnp_algo/dpnp_algo.pxd
> -        DPNP_FN_ASTYPE_EXT
Do we need to keep mapping in `dpnp/backend/kernels/dpnp_krnl_elemwise.cpp` for `DPNP_FN_ASTYPE_EXT` and `DPNP_FN_FLATTEN_EXT` or we can get rid of them?

2023-09-29 16:23 UTC, vtavana commented on dpnp/dpnp_array.py
> -        .. seealso:: :meth:`numpy.ndarray.astype`
Could you add examples for `astype` and `flatten`?

2023-10-03 22:43 UTC, vtavana commented on dpnp/dpnp_iface_manipulation.py
> +def tile(a, reps):
```suggestion
def tile(A, reps):
```

2023-10-03 22:43 UTC, vtavana commented on dpnp/dpnp_iface_manipulation.py
> +    Construct an array by repeating A the number of times given by reps.
```suggestion
    Construct an array by repeating `A` the number of times given by reps.
```

2023-10-03 22:43 UTC, vtavana commented on dpnp/dpnp_iface_manipulation.py
> +        The number of repetitions of `a` along each axis.
```suggestion
        The number of repetitions of `A` along each axis.
```

2023-10-03 22:43 UTC, vtavana commented on dpnp/dpnp_algo/dpnp_algo.pxd
> -        DPNP_FN_EYE_EXT
I think you can also remove `DPNP_FN_EYE`, `DPNP_FN_FLATTEN`, `DPNP_FN_REPEAT`, and `DPNP_FN_REPEAT` in this file.

2023-10-05 18:44 UTC, ndgrigorian commented
@npolina4 
With https://github.com/IntelPython/dpctl/pull/1427 you will no longer need to flatten the repeated array for the `axis=None` case. Array API spec seems to be supporting this behavior.

2023-10-06 15:42 UTC, vtavana approved these changes

2023-10-09 13:02 UTC, antonwolfy commented
The below example works differently with numpy and description:
```python
a = numpy.ones((2, 3), dtype='i4')
b = a.astype('i4', copy=False)

b is a
# Out: True

a = dpnp.ones((2, 3), dtype='i4')
b = a.astype('i4', copy=False)

b is a
# Out: False
```

2023-10-09 14:10 UTC, antonwolfy requested changes

2023-11-28 15:55 UTC, closed without merging