Dpnp ptp
IntelPython/dpnp pull request #715
Opened 2021-05-14 14:55 UTC by Rubtsowa

2021-06-07 14:00 UTC, shssf approved these changes

2021-09-30 15:27 UTC, densmirn approved these changes

2021-10-01 10:32 UTC, Alexander-Makaryev requested changes

2021-10-01 10:32 UTC, Alexander-Makaryev commented on dpnp/backend/kernels/dpnp_krnl_arraycreation.cpp
> +    _DataType* max_arr = reinterpret_cast<_DataType*>(dpnp_memory_alloc_c(size * sizeof(_DataType)));
Where is freeing of this memory?

2021-10-01 10:32 UTC, Alexander-Makaryev commented on dpnp/backend/kernels/dpnp_krnl_arraycreation.cpp
> +    }
Checks like these, that are forward to immediately return from function, should be in the begin of function before any other computations.

2021-10-01 10:32 UTC, Alexander-Makaryev commented on dpnp/backend/kernels/dpnp_krnl_arraycreation.cpp
> +    if ((arr == nullptr) || (result == nullptr))
It looks like that `arr == nullptr` only when `array1_in == nullptr`, is not it?

2021-10-01 11:54 UTC, densmirn commented on dpnp/dpnp_iface_arraycreation.py
> +                return result.dtype.type(result[0])
You could call function `dpnp.convert_single_elem_array_to_scalar` here.

2021-10-01 11:54 UTC, densmirn commented on dpnp/dpnp_iface_arraycreation.py
> +            pass
You could decrease indentations with the following way:
```suggestion
    if not arr_desc:
        pass
    elif axis is not None and not isinstance(axis, int):
        pass
```

2021-10-01 11:54 UTC, densmirn commented on dpnp/backend/kernels/dpnp_krnl_arraycreation.cpp
> +    DPNPC_ptr_adapter<_DataType> result_ptr(result1, size, true, true);
Do we really need `true` parameters for these adapters?

2021-10-05 12:34 UTC, densmirn commented on dpnp/dpnp_algo/dpnp_algo_arraycreation.pyx
> +    func(result.get_data(), arr.get_data(), < size_t * > output_shape.data(), result.ndim, < size_t * > shape_arr.data(), arr.ndim, < size_t * > axis2.data(), axis_size)
Do you really need casting to `< size_t * >`?

2021-10-05 12:34 UTC, densmirn commented on dpnp/backend/include/dpnp_iface.hpp
> +void dpnp_ptp_c(void* result1, void* array1_in, const size_t* res_shape, size_t res_ndim, const size_t* shape, size_t ndim, const size_t* axis, size_t naxis);
Let's make interface of the function similar to interface of `dpnp_matmul_c`. I mean result and input parameters. Parameters `axis` look ok.

2021-10-05 19:00 UTC, Alexander-Makaryev commented
@LukichevaPolina Could you please mark conversations above that were processed? It is hard to understand what is done and what is not. I set "In progress" label, please remove it and request review one more time when you will be ready.

2021-10-06 08:27 UTC, densmirn commented on dpnp/dpnp_algo/dpnp_algo_arraycreation.pyx
> +    func(result.get_data(), arr.get_data(), < size_t * > output_shape.data(), result.ndim, < size_t * > shape_arr.data(), arr.ndim, < size_t * > axis2.data(), axis_size)
Looks like problem is in `custom_arraycreation_1in_1out_func_ptr_t`. Could you please change types `size_t *` to `long *` there?

2021-12-29 16:59 UTC, Alexander-Makaryev approved these changes
LGTM

2021-12-29 17:00 UTC, merged