Unskip gpu tests
IntelPython/dpnp pull request #716
Opened 2021-05-14 18:04 UTC by Rubtsowa

2021-05-14 18:59 UTC, samir-nasibli requested changes
Please provide description why are you disabling this tests.

The name of the PR does not match their entity.

2021-05-14 18:59 UTC, samir-nasibli commented on tests/skipped_tests_gpu.tbl
> +tests/third_party/cupy/fft_tests/test_fft.py::TestRfft_param_13_{n=15, norm=None, shape=(10, 10)}::test_rfft
?

2021-05-14 18:59 UTC, samir-nasibli commented on tests/skipped_tests_gpu.tbl
> +tests/third_party/cupy/creation_tests/test_basic.py::TestBasic::test_zeros_strides
Why are you turning off these tests?

2021-05-14 18:59 UTC, samir-nasibli commented on tests/skipped_tests_gpu.tbl
> +tests/third_party/cupy/creation_tests/test_ranges.py::TestOgrid::test_ogrid5
?

2021-05-15 14:06 UTC, shssf approved these changes

2021-05-18 10:20 UTC, samir-nasibli approved these changes

2021-06-19 14:18 UTC, merged